export enum RoutesPath {
    Home = 'home',
    Login = 'login',
    Autorimessa = 'autorimessa',
    Servizi = 'servizi',
    Statistiche = 'statistiche',
    GestioneUtenti = 'gestione-utenti',
    Logged = 'logged',
    NotFound = '404',
    Auth = 'auth',
    CasLogout = 'caslogout',
    UtenteNonAbilitato = 'utente-non-abilitato',
    Rubrica = 'rubrica',
    RubricaPersonale = 'rubrica-personale',
    TrasferimentoChiamata = 'trasferimento-chiamata',
    Changelog = 'changelog',
    Profilo = 'profilo',
    Preferenze = 'preferenze',
    ImpostazioniSede = 'impostazioni-sede',
    POS = 'POS'
}
