using System;

namespace SO115App.Persistence.Oracle.Classi
{
    public class ORAInterventiChiusi
    {
        /// <SUMMARY>CAMPO INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO DATA_CHIAMATA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime DATA_CHIAMATA { get; set; }

        /// <SUMMARY>CAMPO ORA_CHIAMATA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string ORA_CHIAMATA { get; set; }

        /// <SUMMARY>CAMPO DATA_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime DATA_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO ORA_USCITA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string ORA_USCITA { get; set; }

        /// <SUMMARY>CAMPO TURNO_CHIAMATA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string TURNO_CHIAMATA { get; set; }

        /// <SUMMARY>CAMPO TURNO_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string TURNO_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO COD_TIPOLOGIA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? COD_TIPOLOGIA { get; set; }

        /// <SUMMARY>CAMPO DETTAGLIO_TIPOLOGIA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string DETTAGLIO_TIPOLOGIA { get; set; }

        /// <SUMMARY>CAMPO NOTE_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NOTE_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO LOC_INDIRIZZO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string LOC_INDIRIZZO { get; set; }

        /// <SUMMARY>CAMPO LOCALITA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string LOCALITA { get; set; }

        /// <SUMMARY>CAMPO COD_STRADA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string COD_STRADA { get; set; }

        /// <SUMMARY>CAMPO NUM_CIVICO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NUM_CIVICO { get; set; }

        /// <SUMMARY>CAMPO COD_COMUNE DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? COD_COMUNE { get; set; }

        /// <SUMMARY>CAMPO SIGLA_PROVINCIA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string SIGLA_PROVINCIA { get; set; }

        /// <SUMMARY>CAMPO RICHIEDENTE DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string RICHIEDENTE { get; set; }

        /// <SUMMARY>CAMPO TELE_NUMERO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string TELE_NUMERO { get; set; }

        /// <SUMMARY>CAMPO COMANDO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string COMANDO { get; set; }

        /// <SUMMARY>CAMPO SCHEDA_ALTRO_COMANDO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string SCHEDA_ALTRO_COMANDO { get; set; }

        // <SUMMARY> CAMPO NATURA DELLA TABELLA INTERVENTI_CHIUSI
        /// </SUMMARY>
        public string NATURA { get; set; }

        /// <SUMMARY>CAMPO MATRICOLA_OPERATORE_CHIAMATA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string MATRICOLA_OPERATORE_CHIAMATA { get; set; }

        /// <SUMMARY>CAMPO MATRICOLA_OPERATORE_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string MATRICOLA_OPERATORE_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO STATUS DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string STATUS { get; set; }

        /// <SUMMARY>CAMPO ENTI_INTERVENUTI DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string ENTI_INTERVENUTI { get; set; }

        /// <SUMMARY>CAMPO ORA_CHIUSURA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string ORA_CHIUSURA { get; set; }

        /// <SUMMARY>CAMPO DATA_CHIUSURA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime DATA_CHIUSURA { get; set; }

        /// <SUMMARY>CAMPO FLAG_DOC_SN DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string FLAG_DOC_SN { get; set; }

        /// <SUMMARY>CAMPO RICEVUTA_TRASMESSA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string RICEVUTA_TRASMESSA { get; set; }

        /// <SUMMARY>CAMPO COD_OBIETTIVO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? COD_OBIETTIVO { get; set; }

        /// <SUMMARY>CAMPO COD_STRADA_INCROCIO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string COD_STRADA_INCROCIO { get; set; }

        /// <SUMMARY>CAMPO FLAG_CIV_KM DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string FLAG_CIV_KM { get; set; }

        /// <SUMMARY>CAMPO FLAG_AGGIOR DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string FLAG_AGGIOR { get; set; }

        /// <SUMMARY>CAMPO NOME_STRADA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NOME_STRADA { get; set; }

        /// <SUMMARY>CAMPO EDGID_STRADA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? EDGID_STRADA { get; set; }

        /// <SUMMARY>CAMPO NOME_STRADA_INCROCIO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NOME_STRADA_INCROCIO { get; set; }

        /// <SUMMARY>CAMPO EDGID_STRADA_INCROCIO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? EDGID_STRADA_INCROCIO { get; set; }

        /// <SUMMARY>CAMPO COD_PRIORITA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string COD_PRIORITA { get; set; }

        /// <SUMMARY>CAMPO PROGR_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? PROGR_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO CODICE_PI DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? CODICE_PI { get; set; }

        /// <SUMMARY>CAMPO INTERVENTO_RILEVANTE DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string INTERVENTO_RILEVANTE { get; set; }

        /// <SUMMARY>CAMPO BOSCHI DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? BOSCHI { get; set; }

        /// <SUMMARY>CAMPO CAMPI DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? CAMPI { get; set; }

        /// <SUMMARY>CAMPO STERPAGLIE DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? STERPAGLIE { get; set; }

        /// <SUMMARY>CAMPO X DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? X { get; set; }

        /// <SUMMARY>CAMPO Y DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? Y { get; set; }

        /// <SUMMARY>CAMPO ID_INCROCIO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? ID_INCROCIO { get; set; }

        /// <SUMMARY>CAMPO CHIAMATA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? CHIAMATA { get; set; }

        /// <SUMMARY>CAMPO DESC_COMUNE DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string DESC_COMUNE { get; set; }

        /// <SUMMARY>CAMPO PALAZZO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string PALAZZO { get; set; }

        /// <SUMMARY>CAMPO SCALA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string SCALA { get; set; }

        /// <SUMMARY>CAMPO PIANO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string PIANO { get; set; }

        /// <SUMMARY>CAMPO INTERNO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string INTERNO { get; set; }

        /// <SUMMARY>CAMPO NUM_FONOGRAMMA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NUM_FONOGRAMMA { get; set; }

        /// <SUMMARY>CAMPO NUM_PROTOCOLLO_FONO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string NUM_PROTOCOLLO_FONO { get; set; }

        /// <SUMMARY>CAMPO CIVICO_VICINO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string CIVICO_VICINO { get; set; }

        /// <SUMMARY>CAMPO DATAORA_ARRIVO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime? DATAORA_ARRIVO { get; set; }

        /// <SUMMARY>CAMPO DUMMY_SIGLA_PROVENIENZA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string DUMMY_SIGLA_PROVENIENZA { get; set; }

        /// <SUMMARY>CAMPO DUMMY_DATA_EXPORT DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime? DUMMY_DATA_EXPORT { get; set; }

        /// <SUMMARY>CAMPO DUMMY_NUM_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? DUMMY_NUM_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO DUMMY_DATA_INTERVENTO DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public DateTime? DUMMY_DATA_INTERVENTO { get; set; }

        /// <SUMMARY>CAMPO ID_112 DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public decimal? ID_112 { get; set; }

        /// <SUMMARY>CAMPO ZONA_EMERGENZA DELLA TABELLA INTERVENTI_CHIUSI</SUMMARY>
        public string ZONA_EMERGENZA { get; set; }
    }
}
