namespace SO115App.Models.Classi.Concorrenza
{
    public enum TipoOperazione
    {
        Richiesta,
        Mezzo,
        Squadra,
        ChiusuraChiamata,
        ChiusuraIntervento,
        Modifica,
        Trasferimento,
        InvioPartenza,
        Allerta,
        CambioStatoPartenza,
        GestisciPartenza,
        Sganciamento,
        RegistrazioneSchedaContatto,
        ModificaPos,
        EliminaPos,
        ModificaPianiDiscendenti,
        EliminaPianiDiscendenti,
        ModificaDettaglioTipologia,
        EliminaDettaglioTipologia,
        ModificaTriage,
        EliminaTriage,
        AggiungiRuoloUtente,
        EliminaRuoloUtente,
        ModificaRuoloUtente,
        EliminaUtente,
        All
    }
}
