//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wrapper.cap.it/", ConfigurationName="CapWrapper")]
public interface CapWrapper
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    esito acceptFeedMessage(string feedData, string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    System.Threading.Tasks.Task<esito> acceptFeedMessageAsync(string feedData, string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    esito acceptSatMessage(string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    System.Threading.Tasks.Task<esito> acceptSatMessageAsync(string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    esito receiveMessage(string token, string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    System.Threading.Tasks.Task<esito> receiveMessageAsync(string token, string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    esito acceptMessage(string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resultMessage")]
    System.Threading.Tasks.Task<esito> acceptMessageAsync(string inputMessage);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="welcomeMessage")]
    esito welcome();
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="welcomeMessage")]
    System.Threading.Tasks.Task<esito> welcomeAsync();
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wrapper.cap.it/")]
public partial class esito
{
    
    private string codiceField;
    
    private string descrizioneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string codice
    {
        get
        {
            return this.codiceField;
        }
        set
        {
            this.codiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string descrizione
    {
        get
        {
            return this.descrizioneField;
        }
        set
        {
            this.descrizioneField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CapWrapperChannel : CapWrapper, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CapWrapperClient : System.ServiceModel.ClientBase<CapWrapper>, CapWrapper
{
    
    public CapWrapperClient()
    {
    }
    
    public CapWrapperClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CapWrapperClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CapWrapperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CapWrapperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public esito acceptFeedMessage(string feedData, string inputMessage)
    {
        return base.Channel.acceptFeedMessage(feedData, inputMessage);
    }
    
    public System.Threading.Tasks.Task<esito> acceptFeedMessageAsync(string feedData, string inputMessage)
    {
        return base.Channel.acceptFeedMessageAsync(feedData, inputMessage);
    }
    
    public esito acceptSatMessage(string inputMessage)
    {
        return base.Channel.acceptSatMessage(inputMessage);
    }
    
    public System.Threading.Tasks.Task<esito> acceptSatMessageAsync(string inputMessage)
    {
        return base.Channel.acceptSatMessageAsync(inputMessage);
    }
    
    public esito receiveMessage(string token, string inputMessage)
    {
        return base.Channel.receiveMessage(token, inputMessage);
    }
    
    public System.Threading.Tasks.Task<esito> receiveMessageAsync(string token, string inputMessage)
    {
        return base.Channel.receiveMessageAsync(token, inputMessage);
    }
    
    public esito acceptMessage(string inputMessage)
    {
        return base.Channel.acceptMessage(inputMessage);
    }
    
    public System.Threading.Tasks.Task<esito> acceptMessageAsync(string inputMessage)
    {
        return base.Channel.acceptMessageAsync(inputMessage);
    }
    
    public esito welcome()
    {
        return base.Channel.welcome();
    }
    
    public System.Threading.Tasks.Task<esito> welcomeAsync()
    {
        return base.Channel.welcomeAsync();
    }
}
